services:
  nuxt-dev:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.nuxt
      - /app/.output
    ports:
      - "3000:3000"
    environment:
      - NUXT_ENV_LOCAL_DB=true
      - NUXT_ENV_D1_DATABASE_ID=local
    command: sh -c "npx wrangler d1 execute metnav-db --local --file=./migrations/init.sql && npm run dev"